CREATE DATABASE QLCUAHANGGIAY
USE QLCUAHANGGIAY
CREATE TABLE TAIKHOAN(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	tenTk VARCHAR(30)NOT NULL UNIQUE,
	matKhau NVARCHAR(30)NOT NULL
)
CREATE TABLE LOAITAIKHOAN(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	tenLoai NVARCHAR(30) NULL UNIQUE,
)
CREATE TABLE CTTAIKHOAN(
	idTK INT NOT NULL,
	idLoaiTk INT NOT NULL,
	CONSTRAINT FK_CTTAIKHOAN_TAIKHOAN FOREIGN KEY(idTK) REFERENCES dbo.TAIKHOAN(id),
	CONSTRAINT FK_CTTAIKHOAN_LOAITAIKHOAN FOREIGN KEY(idLoaiTk) REFERENCES dbo.LOAITAIKHOAN(id),
	CONSTRAINT PK_CTTAIKHOAN PRIMARY KEY(idTK,idLoaiTk)
)

CREATE TABLE ONGCHU(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30)NULL,
	diaChi NVARCHAR(50)NULL,
	gioiTinh NVARCHAR(30) NULL,
	ngaySinh DATE NULL,
	sdt VARCHAR(30) NULL,
	avatar IMAGE NULL,
	idTK INT NOT NULL,
	CONSTRAINT FK_ONGCHU_TK FOREIGN KEY(idTK) REFERENCES dbo.TAIKHOAN(id)
)

CREATE TABLE CUAHANG(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30) NULL,
	diadiem NVARCHAR(50) NULL,
)
CREATE TABLE CTONGCHU(
	idOngChu INT NOT NULL,
	idCuaHang INT NOT NULL,
	CONSTRAINT FK_CTONGCHU_ONGCHU FOREIGN KEY(idOngChu)REFERENCES dbo.ONGCHU(id),
	CONSTRAINT FK_CTONGCHU_CUAHAG FOREIGN KEY(idCuaHang) REFERENCES dbo.CUAHANG(id),
	CONSTRAINT PK_CTONGCHU PRIMARY KEY(idOngChu,idCuaHang)

)
CREATE TABLE HANGGIAY(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30)NULL UNIQUE,
	avatar IMAGE NULL

)

CREATE TABLE CTHANGGIAY(
	idCH INT NOT NULL ,
	idHang INT NOT NULL,
	CONSTRAINT FK_CTHANGGIAY_CUAHANG FOREIGN KEY(idCH) REFERENCES dbo.CUAHANG(id),
	CONSTRAINT FK_CTHANGGIAY_HANGGIAY FOREIGN KEY(idHang) REFERENCES dbo.HANGGIAY(id),
	CONSTRAINT PK_CTHANGGIAY PRIMARY KEY(idCH,idHang)
)
CREATE TABLE DONGSP(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten VARCHAR(30) NULL UNIQUE
)

CREATE TABLE CTDONG(
	idHang INT NOT NULL,
	idDong INT NOT NULL,
	CONSTRAINT FK_CTDONG_HANG FOREIGN KEY(idHang) REFERENCES dbo.HANGGIAY(id),
	CONSTRAINT Fk_CTDONG_DONGSP FOREIGN KEY(idDong) REFERENCES dbo.DONGSP(id),
	CONSTRAINT PK_CTDONG PRIMARY KEY(idHang,idDong)
)
CREATE TABLE LOAIGIAY(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30) NULL UNIQUE,
	idDong INT NOT NULL,
	idHang INT NOT NULL,
	giaNhap INT NULL,
	giaBan INT NULL,
	avatar IMAGE NULL,
	CONSTRAINT FK_LOAIGIAY_DONGSP FOREIGN KEY(idDong) REFERENCES dbo.DONGSP(id),
	CONSTRAINT FK_LOAIGIAY_HANGGIAY FOREIGN KEY(idHang) REFERENCES dbo.HANGGIAY(id)
)


CREATE TABLE CHUCVU(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30) NULL UNIQUE
)


CREATE TABLE NHANVIEN(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	idCH INT NOT NULL,
	idCV INT NOT NULL,
	idTK INT NOT NULL,
	ten NVARCHAR(30) NULL,
	diaChi NVARCHAR(30)NULL,
	ngaySinh DATE NULL,
	gioiTinh NVARCHAR(30)NULL,
	luong INT NULL,
	sdt VARCHAR(30)NULL,
	avatar IMAGE NULL,
	CONSTRAINT FK_NHANVIEN_CUAHANG FOREIGN KEY(idCH) REFERENCES dbo.CUAHANG(id),
	CONSTRAINT FK_NHANVIEN_CHUCVU FOREIGN KEY(idCV) REFERENCES dbo.CHUCVU(id),
	CONSTRAINT FK_NHANVIEN_TAIKHOAN FOREIGN KEY(idTK) REFERENCES dbo.TAIKHOAN(id)
)
CREATE TABLE KHACHHANG(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30) NULL,
	diaChi NVARCHAR(30)NULL,
	ngaySinh DATE NULL,
	gioiTinh NVARCHAR(30)NULL,
	sdt VARCHAR(30)NULL,

)
CREATE TABLE HOADON(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	idNV INT NOT NULL,
	idKH INT NOT NULL,
	ngayTao DATE NULL,
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(idNV) REFERENCES dbo.NHANVIEN(id),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(idKH) REFERENCES dbo.KHACHHANG(id)
) 
CREATE TABLE GIAY(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	idLoai INT NOT NULL,
	idCuaHang INT NOT NULL,
	idHoaDon INT NOT NULL,
	noiSx NVARCHAR(30) NOT NULL,
	mauSac NVARCHAR(30) NOT NULL,
	size INT NOT NULL,
	gioiTinh VARCHAR(30) NOT NULL,
	CONSTRAINT FK_GIAY_LOAIGIAY FOREIGN KEY(idLoai) REFERENCES dbo.LOAIGIAY(id),
	CONSTRAINT FK_GIAY_CUAHANG FOREIGN KEY(idCuaHang) REFERENCES dbo.CUAHANG(id),
	CONSTRAINT FK_IGIAY_HOADON FOREIGN KEY(idHoaDon) REFERENCES dbo.HOADON(id),
)


CREATE TABLE THANNHAN(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	ten NVARCHAR(30) NULL,
	diaChi NVARCHAR(30)NULL,
	ngaySinh DATE NULL,
	gioiTinh NVARCHAR(30) NULL,
	sdt VARCHAR(30)NULL
)

CREATE TABLE CTTHANNHAN(
	idNV INT NOT NULL ,
	idTN INT NOT NULL,
	quanHe NVARCHAR(30)NULL,
	CONSTRAINT FK_CTTHANNHAN_NHANVIEN FOREIGN KEY(idNV) REFERENCES dbo.NHANVIEN(id),
	CONSTRAINT FK_CTTHANNHAN_THANNHAN FOREIGN KEY(idTN) REFERENCES dbo.THANNHAN(id),
	CONSTRAINT PK_CTTHANNHAN PRIMARY KEY(idNV,idTN)
)




INSERT INTO dbo.HANGGIAY VALUES(N'ADIDAS',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'NIKE',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'PUMA',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'CONVERSE',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'NEW BALANCE',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'JORDAN',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'REEBOOK',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'VANS',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'CONVERSE',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'PUMA',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'FILA',NULL)
INSERT INTO dbo.HANGGIAY VALUES(N'THƯỢNG ĐÌNH',NULL)


INSERT INTO dbo.DONGSP VALUES('Originals')
INSERT INTO dbo.DONGSP VALUES('Football')
INSERT INTO dbo.DONGSP VALUES('Running')
INSERT INTO dbo.DONGSP VALUES('Training')
INSERT INTO dbo.DONGSP VALUES('Basketball')
INSERT INTO dbo.DONGSP VALUES('Tennis')
INSERT INTO dbo.DONGSP VALUES('OutDoor')
INSERT INTO dbo.DONGSP VALUES('LifeStyle')
INSERT INTO dbo.DONGSP VALUES('Jordan')
INSERT INTO dbo.DONGSP VALUES('Sneaker')

INSERT INTO dbo.CUAHANG VALUES(N'CH1',N'Hà Nội')
INSERT INTO dbo.CUAHANG VALUES(N'CH2',N'Hà Nam')
INSERT INTO dbo.CUAHANG VALUES(N'CH3',N'Hà Tĩnh')
INSERT INTO dbo.CUAHANG VALUES(N'CH4',N'Bắc Ninh')
INSERT INTO dbo.CUAHANG VALUES(N'CH5',N'Tp.HCM')





SELECT*FROM dbo.HANGGIAY
SELECT*FROM dbo.CUAHANG
SELECT*FROM dbo.LOAIGIAY
SELECT*FROM dbo.DONGSP
SELECT*FROM dbo.CTHANGGIAY
SELECT*FROM dbo.HOADON
SELECT*FROM dbo.GIAY
SELECT*FROM dbo.KHACHHANG
SELECT*FROM dbo.NHANVIEN
SELECT*FROM dbo.CHUCVU

INSERT INTO dbo.CHUCVU VALUES(  N'Nhân Viên'),
							(  N'Quản lí'),
							(  N'Bảo vệ')

INSERT INTO dbo.TAIKHOAN
VALUES
(   'Nhanvien01', -- tenTk - varchar(30)
    N'123' -- matKhau - nvarchar(30)
    )

INSERT INTO dbo.LOAITAIKHOAN VALUES(N'Nhân Viên' )

INSERT INTO dbo.CTTAIKHOAN VALUES(   1,  1   )

INSERT INTO dbo.KHACHHANG VALUES(  N'Minh',N'Ha Noi',NULL, N'Nam','0213232')

INSERT INTO dbo.NHANVIEN VALUES
	(   1,         -- idCH - int
	    1,         -- idCV - int
	    1,         -- idTK - int
	    N'Tran Van A',       -- ten - nvarchar(30)
	    N'Ha Noi',       -- diaChi - nvarchar(30)
	    NULL, -- ngaySinh - date
	    N'Nam',       -- gioiTinh - nvarchar(30)
	    5000000,         -- luong - int
	    '012132132',        -- sdt - varchar(30)
	    NULL       -- avatar - image
	    )
INSERT INTO dbo.HOADON VALUES(3,1,'2022-07-22')
INSERT INTO dbo.HOADON VALUES(3,1,'2022-07-22')
INSERT INTO dbo.HOADON VALUES(3,1,'2023-07-22')


INSERT INTO dbo.LOAIGIAY VALUES(N'Ultraboost22',10,1,2000000,2500000,NULL)
INSERT INTO dbo.LOAIGIAY VALUES(N'Ultraboost DNA Climacool',10,1,3000000,3500000,NULL)
INSERT INTO dbo.LOAIGIAY VALUES(N'Busenitz Vintage',10,1,4000000,4500000,NULL)
INSERT INTO dbo.LOAIGIAY VALUES(N'Gazelle',10,1,5000000,5500000,NULL)
INSERT INTO dbo.LOAIGIAY VALUES(N'Estrail 2.0',10,1,6000000,6500000,NULL)
INSERT INTO dbo.LOAIGIAY VALUES(N'OZWEEGO',10,1,7000000,7500000,NULL)


INSERT INTO dbo.CTHANGGIAY VALUES(1,1)
INSERT INTO dbo.CTHANGGIAY VALUES(1,2)
INSERT INTO dbo.CTHANGGIAY VALUES(1,3)
INSERT INTO dbo.CTHANGGIAY VALUES(2,1)
INSERT INTO dbo.CTHANGGIAY VALUES(2,2)
INSERT INTO dbo.CTHANGGIAY VALUES(3,1)
INSERT INTO dbo.CTHANGGIAY VALUES(3,5)
INSERT INTO dbo.CTHANGGIAY VALUES(3,4)


SELECT*FROM dbo.GIAY

INSERT INTO dbo.GIAY VALUES(3,2,10,N'Trung Quốc',N'Vàng',25,N'Nam')
INSERT INTO dbo.GIAY VALUES(3,2,10,N'Mĩ',N'Vàng',25,N'Nam')
INSERT INTO dbo.GIAY VALUES(3,2,10,N'Trung Quốc',N'Vàng',25,N'Nam')








