/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import java.util.ArrayList;
import javax.swing.JPanel;
import utility.ChuyenManHinh;
import utility.DanhMuc;
import view.Xe_Form;
/**
 *
 * @author Admin
 */
public class HeThongChoThueXe extends javax.swing.JFrame {

    /** Creates new form HeThongChoThueXe */
    private JPanel childPan;
    public HeThongChoThueXe() {
        initComponents();
        ChuyenManHinh cm = new ChuyenManHinh(pnView);
        cm.setView(pnQlXe, lblQuanLyXe);    
        ArrayList<DanhMuc> _lst = new ArrayList<>();
        _lst.add(new DanhMuc("Trang Chủ", pnTrangChu, lblTrangChu));
        _lst.add(new DanhMuc("Quản Lý Xe", pnQlXe, lblQuanLyXe));
        _lst.add(new DanhMuc("Hợp đồng", pnHopDong, lblHopDong));
        _lst.add(new DanhMuc("Khuyến mãi", pnlKhuyenMai, lblKhuyenmai));
        _lst.add(new DanhMuc("Nhân viên", pnlNV, lblNV));
        _lst.add(new DanhMuc("Khách hàng", pnlKhachHang, lblKhachHang));
        _lst.add(new DanhMuc("Tài khoản", pnlTaiKhoan, lblTaiKhoan));
        cm.setEvent(_lst);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDoiTaiKhoan = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        pnQlXe = new javax.swing.JPanel();
        lblQuanLyXe = new javax.swing.JLabel();
        pnHopDong = new javax.swing.JPanel();
        lblHopDong = new javax.swing.JLabel();
        pnlKhuyenMai = new javax.swing.JPanel();
        lblKhuyenmai = new javax.swing.JLabel();
        pnlNV = new javax.swing.JPanel();
        lblNV = new javax.swing.JLabel();
        pnlKhachHang = new javax.swing.JPanel();
        lblKhachHang = new javax.swing.JLabel();
        pnlTaiKhoan = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Pro1014\\PRO1014\\PRO1014\\image\\LoginIcon.png")); // NOI18N
        jLabel1.setText("Car Rental");

        btnDoiTaiKhoan.setBackground(new java.awt.Color(51, 255, 204));
        btnDoiTaiKhoan.setIcon(new javax.swing.ImageIcon("D:\\Pro1014\\PRO1014\\PRO1014\\image\\user.png")); // NOI18N
        btnDoiTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiTaiKhoanActionPerformed(evt);
            }
        });

        btnOut.setIcon(new javax.swing.ImageIcon("D:\\Pro1014\\PRO1014\\PRO1014\\image\\out.png")); // NOI18N
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Pro1014\\PRO1014\\PRO1014\\image\\account.png")); // NOI18N
        jLabel2.setText(":-");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("I");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Pro1014\\PRO1014\\PRO1014\\image\\LoginIcon.png")); // NOI18N
        jLabel5.setText("Rental Car");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(btnDoiTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(141, 141, 141))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 80));
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTrangChu.setBackground(new java.awt.Color(51, 255, 204));

        lblTrangChu.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(102, 102, 0));
        lblTrangChu.setText("Trang Chủ");

        javax.swing.GroupLayout pnTrangChuLayout = new javax.swing.GroupLayout(pnTrangChu);
        pnTrangChu.setLayout(pnTrangChuLayout);
        pnTrangChuLayout.setHorizontalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnTrangChuLayout.setVerticalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 60));

        pnQlXe.setBackground(new java.awt.Color(153, 255, 204));
        pnQlXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQlXeMouseClicked(evt);
            }
        });
        pnQlXe.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                pnQlXeCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        lblQuanLyXe.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblQuanLyXe.setForeground(new java.awt.Color(0, 0, 153));
        lblQuanLyXe.setText("Quản lý xe");

        javax.swing.GroupLayout pnQlXeLayout = new javax.swing.GroupLayout(pnQlXe);
        pnQlXe.setLayout(pnQlXeLayout);
        pnQlXeLayout.setHorizontalGroup(
            pnQlXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyXe, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnQlXeLayout.setVerticalGroup(
            pnQlXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyXe, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnQlXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, -1));

        pnHopDong.setBackground(new java.awt.Color(153, 255, 204));

        lblHopDong.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblHopDong.setForeground(new java.awt.Color(0, 0, 153));
        lblHopDong.setText("Hợp đồng");

        javax.swing.GroupLayout pnHopDongLayout = new javax.swing.GroupLayout(pnHopDong);
        pnHopDong.setLayout(pnHopDongLayout);
        pnHopDongLayout.setHorizontalGroup(
            pnHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnHopDongLayout.setVerticalGroup(
            pnHopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel1.add(pnHopDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, -1));

        pnlKhuyenMai.setBackground(new java.awt.Color(153, 255, 204));

        lblKhuyenmai.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblKhuyenmai.setForeground(new java.awt.Color(0, 0, 153));
        lblKhuyenmai.setText("Khuyến mãi");

        javax.swing.GroupLayout pnlKhuyenMaiLayout = new javax.swing.GroupLayout(pnlKhuyenMai);
        pnlKhuyenMai.setLayout(pnlKhuyenMaiLayout);
        pnlKhuyenMaiLayout.setHorizontalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlKhuyenMaiLayout.setVerticalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnlKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        pnlNV.setBackground(new java.awt.Color(153, 255, 204));

        lblNV.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        lblNV.setForeground(new java.awt.Color(0, 0, 153));
        lblNV.setText("Nhân viên");

        javax.swing.GroupLayout pnlNVLayout = new javax.swing.GroupLayout(pnlNV);
        pnlNV.setLayout(pnlNVLayout);
        pnlNVLayout.setHorizontalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNV, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlNVLayout.setVerticalGroup(
            pnlNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNV, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanel1.add(pnlNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, -1));

        pnlKhachHang.setBackground(new java.awt.Color(153, 255, 204));

        lblKhachHang.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(0, 0, 153));
        lblKhachHang.setText("Khách hàng");

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanel1.add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, -1));

        pnlTaiKhoan.setBackground(new java.awt.Color(153, 255, 204));

        lblTaiKhoan.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(0, 0, 153));
        lblTaiKhoan.setText("Tài khoản");

        javax.swing.GroupLayout pnlTaiKhoanLayout = new javax.swing.GroupLayout(pnlTaiKhoan);
        pnlTaiKhoan.setLayout(pnlTaiKhoanLayout);
        pnlTaiKhoanLayout.setHorizontalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pnlTaiKhoanLayout.setVerticalGroup(
            pnlTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(pnlTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, -1));

        jPanel10.setBackground(new java.awt.Color(153, 255, 204));

        jLabel13.setFont(new java.awt.Font("Zilla Slab Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("S");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 570));

        javax.swing.GroupLayout pnViewLayout = new javax.swing.GroupLayout(pnView);
        pnView.setLayout(pnViewLayout);
        pnViewLayout.setHorizontalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnViewLayout.setVerticalGroup(
            pnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        getContentPane().add(pnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 800, 632));

        setSize(new java.awt.Dimension(1064, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnQlXeCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pnQlXeCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pnQlXeCaretPositionChanged

    private void pnQlXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQlXeMouseClicked
        // TODO add your handling code here:
        //        childPan = new Xe_Form();
        //        pnQL_xe.removeAll();
        //        pnQL_xe.add(childPan);
        //        pnQL_xe.validate();
        showPanel(new Xe_Form());
    }//GEN-LAST:event_pnQlXeMouseClicked

    private void btnDoiTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiTaiKhoanActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        
        lg.setVisible(true);
    }//GEN-LAST:event_btnDoiTaiKhoanActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnOutActionPerformed
    private void showPanel(JPanel jpanel){
        childPan = jpanel;
        pnView.removeAll();
        pnView.add(childPan);
        pnView.validate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeThongChoThueXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeThongChoThueXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeThongChoThueXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeThongChoThueXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeThongChoThueXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiTaiKhoan;
    private javax.swing.JButton btnOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblHopDong;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhuyenmai;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblQuanLyXe;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JPanel pnHopDong;
    private javax.swing.JPanel pnQlXe;
    private javax.swing.JPanel pnTrangChu;
    private javax.swing.JPanel pnView;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlKhuyenMai;
    private javax.swing.JPanel pnlNV;
    private javax.swing.JPanel pnlTaiKhoan;
    // End of variables declaration//GEN-END:variables

}
