/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import service.Impl.KhachHangServiceImpl;
import service.KhachHangService;

/**
 *
 * @author Admin
 */
public class KhachHangForm extends javax.swing.JPanel {
    
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<KhachHang> listkh = new ArrayList<>();
    private KhachHangService khachHangService = new KhachHangServiceImpl();

    /**
     * Creates new form KhachHangForm
     */
    public KhachHangForm() {
        initComponents();
        tblkhachhang.setModel(dtm);
        String[] headers = {"Ma Khach Hang", "Ten Khach Hang", "Gioi Tinh", "Dia Chi", "So Dien Thoai", "Can Cuoc Cong Dan"};
        dtm.setColumnIdentifiers(headers);
        listkh = khachHangService.getAll();
        ShowDataRow(listkh);
    }
    
    private void ShowDataRow(List<KhachHang> lists) {
        dtm.setRowCount(0);
        for (KhachHang x : lists) {
            dtm.addRow(x.todataRow());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        btnTao1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnClearNv1 = new javax.swing.JButton();
        btnSearch1 = new javax.swing.JButton();
        txtSearchKH = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        txtTenKh = new javax.swing.JTextField();
        txtSoDTKH = new javax.swing.JTextField();
        txtDiaChiKH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoCCCD = new javax.swing.JTextField();
        RadioNam = new javax.swing.JRadioButton();
        RadioNu = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(23, 35, 51));

        jPanel6.setBackground(new java.awt.Color(71, 120, 197));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 12))); // NOI18N

        tblkhachhang.setBackground(new java.awt.Color(153, 153, 255));
        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhachhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblkhachhang);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
<<<<<<< HEAD
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
=======
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
>>>>>>> 4988e226ba482cf6feecfd5ed757409be804e9aa
        );

        btnTao1.setBackground(new java.awt.Color(51, 51, 255));
        btnTao1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnTao1.setText("Tạo");
        btnTao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTao1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(51, 51, 255));
        btnSua1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnClearNv1.setBackground(new java.awt.Color(51, 51, 255));
        btnClearNv1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnClearNv1.setText("Làm mới");
        btnClearNv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNv1ActionPerformed(evt);
            }
        });

        btnSearch1.setBackground(new java.awt.Color(51, 51, 255));
        btnSearch1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnSearch1.setText("Tìm kiếm");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(71, 120, 197));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel6.setText("Mã khách");

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel7.setText("Tên khách");

        jLabel8.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel8.setText("Địa chỉ");

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel9.setText("Số điện thoại");

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel10.setText("Giới tính");

        lblMaKH.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblMaKH.setText("_");

        txtTenKh.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N

        txtSoDTKH.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N

        txtDiaChiKH.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel11.setText("Số CCCD");

        txtSoCCCD.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N

        buttonGroup1.add(RadioNam);
        RadioNam.setText("Nam");

        buttonGroup1.add(RadioNu);
        RadioNu.setText("Nữ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbGioiTinhKH, 0, 348, Short.MAX_VALUE)
                    .addComponent(txtTenKh))
=======
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenKh, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(RadioNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RadioNu)
                                .addGap(0, 0, Short.MAX_VALUE)))))
>>>>>>> 4988e226ba482cf6feecfd5ed757409be804e9aa
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoDTKH)
                    .addComponent(txtDiaChiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtSoCCCD))
                .addGap(55, 55, 55))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtSoDTKH)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTenKh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(RadioNam)
                            .addComponent(RadioNu))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTao1)
                        .addGap(44, 44, 44)
                        .addComponent(btnSua1)
                        .addGap(48, 48, 48)
                        .addComponent(btnClearNv1)
                        .addGap(76, 76, 76)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTao1)
                    .addComponent(btnSua1)
                    .addComponent(btnClearNv1)
                    .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fill(int i) {
        KhachHang kh = listkh.get(i);
        lblMaKH.setText(kh.getMaKh());
        txtTenKh.setText(kh.getTenKh());
        txtDiaChiKH.setText(kh.getDiaChi());
        txtSoCCCD.setText(kh.getCccd());
        txtSoDTKH.setText(kh.getSdt());
        if (kh.isGioiTinh()) {
            RadioNam.setSelected(true);
        } else {
            RadioNu.setSelected(true);
        }
    }

    private void btnTao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTao1ActionPerformed
        // TODO add your handling code here:
        String makh = khachHangService.ZenMa();
        String tenkh = txtTenKh.getText();
        boolean gt = RadioNam.isSelected();
        String dc = txtDiaChiKH.getText();
        String sdt = txtSoDTKH.getText();
        String cccd = txtSoCCCD.getText();
        KhachHang kh = new KhachHang(makh, tenkh, dc, sdt, cccd, gt);
        JOptionPane.showMessageDialog(this, khachHangService.Them(kh));
        listkh = khachHangService.getAll();
        ShowDataRow(listkh);
    }//GEN-LAST:event_btnTao1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        String makh = khachHangService.ZenMa();
        String tenkh = txtTenKh.getText();
        boolean gt = RadioNam.isSelected();
        String dc = txtDiaChiKH.getText();
        String sdt = txtSoDTKH.getText();
        String cccd = txtSoCCCD.getText();
        KhachHang kh = new KhachHang(makh, tenkh, dc, sdt, cccd, gt);
        JOptionPane.showMessageDialog(this, khachHangService.Sua(kh, tenkh));
        listkh = khachHangService.getAll();
        ShowDataRow(listkh);
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnClearNv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNv1ActionPerformed
        // TODO add your handling code here:
        lblMaKH.setText("");
        txtTenKh.setText("");
        txtDiaChiKH.setText("");
        txtSearchKH.setText("");
        txtSoCCCD.setText("");
        txtSoDTKH.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnClearNv1ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        String tenKh = txtSearchKH.getText();
        List<KhachHang> listSearch = khachHangService.listSearch(listkh, tenKh);
        ShowDataRow(listSearch);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void tblkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhachhangMouseClicked
        // TODO add your handling code here:
        int row = tblkhachhang.getSelectedRow();
        fill(row);
    }//GEN-LAST:event_tblkhachhangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioNam;
    private javax.swing.JRadioButton RadioNu;
    private javax.swing.JButton btnClearNv1;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnTao1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JTable tblkhachhang;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtSearchKH;
    private javax.swing.JTextField txtSoCCCD;
    private javax.swing.JTextField txtSoDTKH;
    private javax.swing.JTextField txtTenKh;
    // End of variables declaration//GEN-END:variables
}
